config/routes.rb
Webapp::Application.routes.draw do
  
  resources :course_comments

  resources :cafeterium_comments

  resources :club_comments

  resources :courses_categories

  resources :clubs

  resources :cafeteria

  resources :cafeteria_categories

  resources :courses

  resources :courses do
    resources :course_comments
  end

 resources :cafeteria do
    resources :cafeterium_comments
  end

  resources :club do
    resources :club_comments
  end

  resources :professors
  resources :ratings
  resources :club_ratings
  resources :cafeteria_ratings
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'sessions#new'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/landing', to: 'users#landing', via: 'get'
  match '/verify/:vfstring', to: 'sessions#verify', via: 'get'
  match '/contactus', to: 'static_pages#contactus', via: 'get'
  match '/sitemap', to: 'static_pages#sitemap', via: 'get'
  match '/showresult', to: 'users#showresult', via: 'post'
  

end

app/models/cafeteria_category.rb
class CafeteriaCategory < ActiveRecord::Base
	has_many :cafeteria

# 	def self.options_for_select
#   order('LOWER(name)').map { |e| [e.name, e.id] }
# end

end

app/controllers/cafeteria_categories_controller.rb
class CafeteriaCategoriesController < ApplicationController
  before_action :set_cafeteria_category, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:new, :show, :edit, :update, :destroy]

  # GET /cafeteria_categories
  # GET /cafeteria_categories.json
  def index
    @cafeteria_categories = CafeteriaCategory.all
  end

  # GET /cafeteria_categories/1
  # GET /cafeteria_categories/1.json
  def show
  end

  # GET /cafeteria_categories/new
  def new
    @cafeteria_category = CafeteriaCategory.new
  end

  # GET /cafeteria_categories/1/edit
  def edit
  end

  # POST /cafeteria_categories
  # POST /cafeteria_categories.json
  def create
    @cafeteria_category = CafeteriaCategory.new(cafeteria_category_params)

    respond_to do |format|
      if @cafeteria_category.save
        format.html { redirect_to @cafeteria_category, notice: 'Cafeteria category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cafeteria_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @cafeteria_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cafeteria_categories/1
  # PATCH/PUT /cafeteria_categories/1.json
  def update
    respond_to do |format|
      if @cafeteria_category.update(cafeteria_category_params)
        format.html { redirect_to @cafeteria_category, notice: 'Cafeteria category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cafeteria_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cafeteria_categories/1
  # DELETE /cafeteria_categories/1.json
  def destroy
    @cafeteria_category.destroy
    respond_to do |format|
      format.html { redirect_to cafeteria_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cafeteria_category
      @cafeteria_category = CafeteriaCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cafeteria_category_params
      params.require(:cafeteria_category).permit(:name)
    end
        def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end

app/helpers/cafeteria_categories_helper.rb
module CafeteriaCategoriesHelper
end

app/views/cafeteria_categories/_form.html.erb
<%= form_for(@cafeteria_category) do |f| %>
  <% if @cafeteria_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cafeteria_category.errors.count, "error") %> prohibited this cafeteria_category from being saved:</h2>

      <ul>
      <% @cafeteria_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cafeteria_categories/edit.html.erb
<h1>Editing cafeteria_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @cafeteria_category %> |
<%= link_to 'Back', cafeteria_categories_path %>

app/views/cafeteria_categories/index.html.erb
<h3>View, rate, and share your experience about a cafeteria item</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cafeteria_categories.each do |cafeteria_category| %>
      <tr>
        <td><%= cafeteria_category.name %></td>
        <td><%= link_to 'Show', cafeteria_category %></td>
        <% if is_admin? %> 
        <td><%= link_to 'Edit', edit_cafeteria_category_path(cafeteria_category) %></td>
        <td><%= link_to 'Destroy', cafeteria_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
      
    <% end %>
  </tbody>
</table>

<br>
<% if is_admin? %> 
<%= link_to 'New Cafeteria category', new_cafeteria_category_path %>
<%end%>

app/views/cafeteria_categories/new.html.erb
<h1>New cafeteria_category</h1>

<%= render 'form' %>

<%= link_to 'Back', cafeteria_categories_path %>

app/views/cafeteria_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cafeteria_category.name %>
</p>

<%= link_to 'Edit', edit_cafeteria_category_path(@cafeteria_category) %> |
<%= link_to 'Back', cafeteria_categories_path %>