config/routes.rb
Webapp::Application.routes.draw do
  
  resources :course_comments

  resources :cafeterium_comments

  resources :club_comments

  resources :courses_categories

  resources :clubs

  resources :cafeteria

  resources :cafeteria_categories

  resources :courses

  resources :courses do
    resources :course_comments
  end

 resources :cafeteria do
    resources :cafeterium_comments
  end

  resources :club do
    resources :club_comments
  end

  resources :professors
  resources :ratings
  resources :club_ratings
  resources :cafeteria_ratings
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'sessions#new'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/landing', to: 'users#landing', via: 'get'
  match '/verify/:vfstring', to: 'sessions#verify', via: 'get'
  match '/contactus', to: 'static_pages#contactus', via: 'get'
  match '/sitemap', to: 'static_pages#sitemap', via: 'get'
  match '/showresult', to: 'users#showresult', via: 'post'
  

end

app/models/cafeterium_comment.rb
class CafeteriumComment < ActiveRecord::Base
  belongs_to :cafeterium
  belongs_to :user
end

app/controllers/cafeterium_comments_controller.rb
class CafeteriumCommentsController < ApplicationController
  before_action :set_cafeterium_comment, only: [:show, :edit, :update, :destroy]

  # GET /cafeterium_comments
  # GET /cafeterium_comments.json
  def index
    @cafeterium_comments = CafeteriumComment.all
  end

  # GET /cafeterium_comments/1
  # GET /cafeterium_comments/1.json
  def show
    @cafeterium_comment = CafeteriumComment.new
  end

  # GET /cafeterium_comments/new
  def new
    @cafeterium = Cafeterium.find params[:cafeterium_id]
    @cafeterium_comment = CafeteriumComment.new
  end

  # GET /cafeterium_comments/1/edit
  def edit
  end

  # POST /cafeterium_comments
  # POST /cafeterium_comments.json
  def create
    @cafeterium = Cafeterium.find params[:cafeterium_id]
    @cafeterium_comment = CafeteriumComment.new(cafeterium_comment_params)
    @cafeterium_comment.cafeterium_id = @cafeterium.id
    @cafeterium_comment.user_id = current_user.id

    respond_to do |format|
      if @cafeterium_comment.save
        format.html { redirect_to @cafeterium, notice: 'Cafeterium comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cafeterium_comment }
      else
        format.html { redirect_to @cafeterium }
        format.json { render json: @cafeterium_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cafeterium_comments/1
  # PATCH/PUT /cafeterium_comments/1.json
  def update
    respond_to do |format|
      if @cafeterium_comment.update(cafeterium_comment_params)
        format.html { redirect_to @cafeterium_comment, notice: 'Cafeterium comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cafeterium_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cafeterium_comments/1
  # DELETE /cafeterium_comments/1.json
  def destroy
    @cafeterium_comment.destroy
    respond_to do |format|
      format.html { redirect_to cafeterium_comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cafeterium_comment
      @cafeterium_comment = CafeteriumComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cafeterium_comment_params
      params.require(:cafeterium_comment).permit(:cafeterium_comment, :params, :comment_made, :cafeterium_id, :user_id)
    end
end

app/views/cafeterium_comments/_form.html.erb
<%= form_for(@cafeterium_comment) do |f| %>
  <% if @cafeterium_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cafeterium_comment.errors.count, "error") %> prohibited this cafeterium_comment from being saved:</h2>

      <ul>
      <% @cafeterium_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment_made %><br>
    <%= f.text_field :comment_made %>
  </div>
  <div class="field">
    <%= f.label :cafeterium_id %><br>
    <%= f.text_field :cafeterium_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cafeterium_comments/edit.html.erb
<h1>Editing cafeterium_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @cafeterium_comment %> |
<%= link_to 'Back', cafeterium_comments_path %>

app/views/cafeterium_comments/index.html.erb
<h1>Listing cafeterium_comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment made</th>
      <th>Cafeterium</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cafeterium_comments.each do |cafeterium_comment| %>
      <tr>
        <td><%= cafeterium_comment.comment_made %></td>
        <td><%= cafeterium_comment.cafeterium %></td>
        <td><%= cafeterium_comment.user %></td>
        <td><%= link_to 'Show', cafeterium_comment %></td>
        <td><%= link_to 'Edit', edit_cafeterium_comment_path(cafeterium_comment) %></td>
        <td><%= link_to 'Destroy', cafeterium_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cafeterium comment', new_cafeterium_comment_path %>

app/views/cafeterium_comments/new.html.erb
<h1>New cafeterium_comment</h1>

<%= render 'form' %>

<%= form_for [@cafeterium, @cafeterium_comment] do |f| %>
   <%= f.text_field :comment_made %>
   <%= f.submit %>
<% end %>

<%= link_to 'Back', cafeterium_comments_path %>

app/views/cafeterium_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment made:</strong>
  <%= @cafeterium_comment.comment_made %>
</p>

<p>
  <strong>Cafeterium:</strong>
  <%= @cafeterium_comment.cafeterium %>
</p>

<p>
  <strong>User:</strong>
  <%= @cafeterium_comment.user %>
</p>

<%= link_to 'Edit', edit_cafeterium_comment_path(@cafeterium_comment) %> |
<%= link_to 'Back', cafeterium_comments_path %>