config/routes.rb
Webapp::Application.routes.draw do
  
  resources :course_comments

  resources :cafeterium_comments

  resources :club_comments

  resources :courses_categories

  resources :clubs

  resources :cafeteria

  resources :cafeteria_categories

  resources :courses

  resources :courses do
    resources :course_comments
  end

 resources :cafeteria do
    resources :cafeterium_comments
  end

  resources :club do
    resources :club_comments
  end

  resources :professors
  resources :ratings
  resources :club_ratings
  resources :cafeteria_ratings
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'sessions#new'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/landing', to: 'users#landing', via: 'get'
  match '/verify/:vfstring', to: 'sessions#verify', via: 'get'
  match '/contactus', to: 'static_pages#contactus', via: 'get'
  match '/sitemap', to: 'static_pages#sitemap', via: 'get'
  match '/showresult', to: 'users#showresult', via: 'post'
  

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:new, :show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all.by_courses_category(params[:courses_category_id])
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course_comment = CourseComment.new
    @course_comments = CourseComment.all
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
  
def filter_params
      params.permit(:courses_category_id)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:course_name, :course_number, :course_description, :professor_id, :year, :courses_category_id)
    end
        def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
	def rating_ballot
	if @rating = current_user.ratings.find_by_course_id(params[:id])
		@rating
	else
		current_user.ratings.new
	end
end

def current_user_rating
	if @rating = current_user.ratings.find_by_course_id(params[:id])
		@rating.value
	else
		"N/A"
	end

end
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
<% if @course.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

  <ul>
    <% @course.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :course_name %><br>
  <%= f.text_field :course_name %>
</div>
<div class="field">
  <%= f.label :course_number %><br>
  <%= f.text_field :course_number %>
</div>
<div class="field">
  <%= f.label :course_description %><br>
  <%= f.text_field :course_description %>
</div>
<div class="field">
  <%= f.label :professor %> 
  <%= f.collection_select(:professor_id, Professor.all,:id, :name)%> 
</div>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.select(:year,[2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018]) %>
  </div>

<div class="field">
  <%= f.label :category %> 
  <%= f.collection_select(:courses_category_id, CoursesCategory.all,:id, :name)%> 
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/courses/_rating.html.erb
<table id="rating">
  <thead>
    <tr>
      <th colspan="2">
        Course Ratings
      </th>
    </tr>
  </thead>
  <tr>
    <td>Average Rating</td>
    <td>
      <%= @course.average_rating %>
    </td>
  </tr>
  <tr>
    <td>Your Rating</td>
    <td>
      <%= current_user_rating %>
    </td>
  </tr>
</table>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h3>View, rate, and share your experience about a course</h3>

<% content_for(:scripts) do %>
<%= javascript_include_tag 'rating_ballot' %>
<% end %>
<form>
<thead>
    <tr>
      <th>Filter By    <%= select_tag "courses_category_id", options_from_collection_for_select( CoursesCategory.all, "id", "name"), prompt: "Course Category" %> </th>
    </tr>
  </thead>
  <%= submit_tag 'Update', class: "btn btn-primary" %> </form>

  <table>
  <thead>
    <tr>
      <th>Course Name</th>
      <th>Course Number</th>
      <th>Course Description</th>
      <th>Professor</th>
      <th>Year</th>
      <th>Rating</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.course_name %></td>
        <td><%= course.course_number %></td>
        <td><%= course.course_description %></td>
        <td><%= course.professor.name %></td>
        <td><%= course.year %>        </td>
        <td><% for i in 1..5 %>
      <% if i <= course.average_rating %>
      <%= image_tag("star-on.png") %>
      <% else %>
      <%= image_tag("star-off.png") %>
      <%end%>
     <% end %>
       (<%= course.ratings.size %>)</td>
        <td><%= link_to 'See More', course_path(course), class: "comment" %><% if is_admin? %>
      <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%end%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--
<ul class="small-block-grid-1">

<thead>
    <tr>
      <th>Filter By<%= collection_select(:courses_category, :name, CoursesCategory.all, :name, :name, prompt: true) %> </th>
    </tr>
  </thead>
  <%= submit_tag 'Update', class: "btn btn-primary" %>
  <% @courses.each do |course| %>
  <li class="border"><%=course.course_name%>
  <td><%= course.year %></td>
    <div class="stars">
    <p><strong>Avg. Rating</strong></p>
   <% for i in 1..5 %>
      <% if i <= course.average_rating %>
      <%= image_tag("star-on.png") %>
      <% else %>
      <%= image_tag("star-off.png") %>
      <%end%>
     <% end %>

    (<%= course.ratings.size %>)

      <%= link_to 'See More', course_path(course), class: "comment" %>
      <% if is_admin? %>
      <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%end%>
    </div>

  </li>

  <%end%>

</ul>
-->
<br>
<% if is_admin? %>
<%= link_to 'New Course', new_course_path %>
<%end%>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<h3>View, rate, and share your experience about a course</h3>
</p>
<p id="notice"><%= notice %></p>

  <font color="red"><%= @course.course_number %>
  <%= @course.course_name %></font>
  (<%= @course.professor.name %>)<br><br>
  <%= @course.course_description %><br>

<% content_for(:scripts) do %>
  <%= javascript_include_tag 'rating_ballot' %>
<% end %>

<div class="starsfloatright">
<%= form_for(rating_ballot, :remote => true, :html => { :class => 'rating_ballot' }) do |f| %>
    <%= f.label("value_1", content_tag(:span, '1'), {:class=>"rating", :id=>"1"}) %>
    <%= radio_button_tag("rating[value]", 1, current_user_rating == 1, :class => 'rating_button') %>
    <%= f.label("value_2", content_tag(:span, '2'), {:class=>"rating", :id=>"2"}) %>
    <%= radio_button_tag("rating[value]", 2, current_user_rating == 2, :class => 'rating_button') %>
    <%= f.label("value_3", content_tag(:span, '3'), {:class=>"rating", :id=>"3"}) %>
    <%= radio_button_tag("rating[value]", 3, current_user_rating == 3, :class => 'rating_button') %>
    <%= f.label("value_4", content_tag(:span, '4'), {:class=>"rating", :id=>"4"}) %>
    <%= radio_button_tag("rating[value]", 4, current_user_rating == 4, :class => 'rating_button') %>
    <%= f.label("value_5", content_tag(:span, '5'), {:class=>"rating", :id=>"5"}) %>
    <%= radio_button_tag("rating[value]", 5, current_user_rating == 5, :class => 'rating_button') %>

    <%= hidden_field_tag("course_id", @course.id) %>
    <%= f.submit :Submit, :id => "rating_submit" %>

    <% end %></div>
<br>
<!--<table id="rating">
  <thead>
    <tr>
      <th colspan="2">
        Course Ratings
      </th>
    </tr>
  </thead>
  <tr>
    <td>Average Rating</td>
    <td>
      <%= @course.average_rating %>
    </td>
  </tr>
  <tr>
    <td>Your Rating</td>
    <td>
      <%= current_user_rating %>
    </td>
  </tr>
</table>-->
<p class="border-for-show"></p>
<font color="red"><p><strong>Comments:</strong></p> </font>
<% @course_comments.each do |course_comment| %>
<% if course_comment.course.id == @course.id %>
   <p><strong> <%= course_comment.user.first_name %>: </strong> <%= course_comment.comment_made %> </p>
<%end%>
<%end%>
<p class="border-for-show"></p>
<font color="red"><p> Post a comment: </p></font>

<%= form_for [@course, @course_comment] do |f| %>
   <%= f.text_field :comment_made %>
   <%= f.submit %>
<% end %>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>