config/routes.rb
Webapp::Application.routes.draw do
  
  resources :course_comments

  resources :cafeterium_comments

  resources :club_comments

  resources :courses_categories

  resources :clubs

  resources :cafeteria

  resources :cafeteria_categories

  resources :courses

  resources :courses do
    resources :course_comments
  end

 resources :cafeteria do
    resources :cafeterium_comments
  end

  resources :club do
    resources :club_comments
  end

  resources :professors
  resources :ratings
  resources :club_ratings
  resources :cafeteria_ratings
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'sessions#new'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/landing', to: 'users#landing', via: 'get'
  match '/verify/:vfstring', to: 'sessions#verify', via: 'get'
  match '/contactus', to: 'static_pages#contactus', via: 'get'
  match '/sitemap', to: 'static_pages#sitemap', via: 'get'
  match '/showresult', to: 'users#showresult', via: 'post'
  

end

app/models/course_comment.rb
class CourseComment < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/controllers/course_comments_controller.rb
class CourseCommentsController < ApplicationController
  before_action :set_course_comment, only: [:show, :edit, :update, :destroy]

  # GET /course_comments
  # GET /course_comments.json
  def index
    @course_comments = CourseComment.all
  end

  # GET /course_comments/1
  # GET /course_comments/1.json
  def show
    @course_comment = CourseComment.new
  end

  # GET /course_comments/new
  def new
    @course = Course.find params[:course_id]
    @course_comment = CourseComment.new
  end

  # GET /course_comments/1/edit
  def edit
  end

  # POST /course_comments
  # POST /course_comments.json
  def create
    @course = Course.find params[:course_id]
    @course_comment = CourseComment.new(course_comment_params)
    @course_comment.course_id = @course.id
    @course_comment.user_id = current_user.id

    respond_to do |format|
      if @course_comment.save
        format.html { redirect_to @course, notice: 'Course comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course_comment }
      else
        format.html { redirect_to @course }
        format.json { render json: @course_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_comments/1
  # PATCH/PUT /course_comments/1.json
  def update
    respond_to do |format|
      if @course_comment.update(course_comment_params)
        format.html { redirect_to @course_comment, notice: 'Course comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_comments/1
  # DELETE /course_comments/1.json
  def destroy
    @course_comment.destroy
    respond_to do |format|
      format.html { redirect_to course_comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_comment
      @course_comment = CourseComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_comment_params
      params.require(:course_comment).permit(:course_comment, :params, :course_id, :user_id, :comment_made)
    end
end

app/views/course_comments/_form.html.erb
<%= form_for(@course_comment) do |f| %>
  <% if @course_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_comment.errors.count, "error") %> prohibited this course_comment from being saved:</h2>

      <ul>
      <% @course_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/course_comments/edit.html.erb
<h1>Editing course_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @course_comment %> |
<%= link_to 'Back', course_comments_path %>

app/views/course_comments/index.html.erb
<h1>Listing course_comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_comments.each do |course_comment| %>
      <tr>
        <td><%= course_comment.comment %></td>
        <td><%= link_to 'Show', course_comment %></td>
        <td><%= link_to 'Edit', edit_course_comment_path(course_comment) %></td>
        <td><%= link_to 'Destroy', course_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course comment', new_course_comment_path %>

app/views/course_comments/new.html.erb
<h1>New course_comment</h1>

<%= render 'form' %>

<%= form_for [@course, @course_comment] do |f| %>
   <%= f.text_field :comment_made %>
   <%= f.submit %>
<% end %>

<%= link_to 'Back', course_comments_path %>

app/views/course_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @course_comment.comment %>
</p>

<%= link_to 'Edit', edit_course_comment_path(@course_comment) %> |
<%= link_to 'Back', course_comments_path %>